# Generated by Django 4.2 on 2023-06-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=20)),
                ('Message', models.TextField()),
                ('Email', models.EmailField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
    ]
